USE [JobAgentDB]
GO

INSERT INTO [ConsultantArea] ([Name])
VALUES
('Personvognsmekaniker'),
('Lastvognsmekaniker'),
('Vejgodstransportuddannelsen'),
('Lager- og terminaluddannelsen'),
('Entreprenør og landbrugsmaskin udd.'),
('Kontoruddannelse med specialer'),
('Handelsuddannelse med specialer'),
('Finansuddannelsen'),
('Eventkoordinator'),
('Detailhandelsuddannelsen med specialer'),
('Skolepraktik'),
('Murer'),
('Træfagenes byggeuddannelse'),
('Byggemontage teknikker'),
('VVS-energi'),
('Bygningsmaler'),
('Bager og konditor'),
('Ernæringsassistent'),
('Gourmetslagter/Industrislagter'),
('Gastronom'),
('Tjener'),
('Receptionist'),
('Data- og kommunikationsuddannelsen'),
('Elektronik- og svagstrømsuddannelsen'),
('Elektriker'),
('Industriteknikeruddannelsen'),
('Værktøjsmager'),
('Procesoperatør'),
('Smed'),
('Landbrugsuddannelsen'),
('Anlægsgartner'),
('Anlægsstruktør'),
('Serviceassistent'),
('Sikkerhedsvagt'),
('Gourmetslagter'),
('Slagter'),
('Tarmrenser'),
('Styrket praktik i Regionen'),
('Fødevare'),
('Merkantil'),
('Industri'),
('Landbrug / Gartner'),
('Transport'),
('Byggeri'),
('SOSU'),
('Ernæringsassistener'),
('Stem'),
('AUB Merkantil')
GO