USE [JobAgentDB]
GO

DECLARE @FromDate DATETIME2(0)
DECLARE @ToDate   DATETIME2(0)

SET @FromDate = '2020-08-30 08:22:13'
SET @ToDate = '2020-08-30 08:22:13'

DECLARE @Seconds INT = DATEDIFF(SECOND, @FromDate, @ToDate)
DECLARE @Random INT = ROUND(((@Seconds-1) * RAND()), 0)

SELECT DATEADD(SECOND, @Random, @FromDate)

DECLARE @deadDate datetime = DATEADD(YEAR, RAND(255) , DATEADD(SECOND, @Random, @FromDate))

-- Insert dummy data for job vacancies.
INSERT INTO
	[JobAdvert] (
		[Title],[Email],[PhoneNumber],[JobDescription],[JobLocation],[JobRegisteredDate],[DeadlineDate],[SourceURL],[CompanyId],[CategoryId],[SpecializationId]
	)
VALUES
('Ikke kategoriseret.', 'test@nc.dk', '03157856', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
'Ikke Påvist', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'google.dk', 1, 0, 0),

('Anlægsgartner på tryk', 'na@na.dk', '01234567',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 1, 1, 0),

('Buschauffør i kollektiv trafik', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis convallis convallis tellus id interdum velit laoreet. Odio pellentesque diam volutpat commodo sed egestas. Molestie at elementum eu facilisis. Erat velit scelerisque in dictum non consectetur a erat nam. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Massa tincidunt nunc pulvinar sapien. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Quam vulputate dignissim suspendisse in est ante in nibh. Arcu risus quis varius quam quisque id diam. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. A diam sollicitudin tempor id eu.

Fusce id velit ut tortor pretium viverra suspendisse potenti. Libero enim sed faucibus turpis in eu mi. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Neque gravida in fermentum et sollicitudin ac. Tempor orci dapibus ultrices in iaculis nunc sed. Orci a scelerisque purus semper eget duis at tellus. Integer vitae justo eget magna fermentum iaculis eu. Nullam non nisi est sit amet. Erat velit scelerisque in dictum non consectetur a erat nam. Magna sit amet purus gravida quis blandit turpis cursus in.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 2, 9, 9),

('Konditor i det fri', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed vulputate odio ut enim. Vitae semper quis lectus nulla at volutpat diam. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Id leo in vitae turpis massa sed elementum tempus egestas. Sed enim ut sem viverra aliquet eget sit amet. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Volutpat lacus laoreet non curabitur gravida arcu. Vitae suscipit tellus mauris a diam maecenas. Orci nulla pellentesque dignissim enim sit amet. Sit amet consectetur adipiscing elit ut aliquam purus sit. In nulla posuere sollicitudin aliquam ultrices. Eu sem integer vitae justo eget magna fermentum iaculis. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Nec feugiat nisl pretium fusce id velit ut tortor. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sit amet purus gravida quis blandit. Neque sodales ut etiam sit.

Aenean vel elit scelerisque mauris pellentesque. Nunc id cursus metus aliquam eleifend mi. Euismod quis viverra nibh cras pulvinar mattis. Egestas congue quisque egestas diam. Ipsum nunc aliquet bibendum enim. Faucibus nisl tincidunt eget nullam non nisi est sit. Fames ac turpis egestas integer eget aliquet nibh. Cras ornare arcu dui vivamus. Habitant morbi tristique senectus et netus. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Est ante in nibh mauris cursus. Sed augue lacus viverra vitae. Consequat interdum varius sit amet mattis vulputate. Id nibh tortor id aliquet lectus proin nibh. In hendrerit gravida rutrum quisque non tellus orci. Auctor augue mauris augue neque. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Erat nam at lectus urna duis convallis.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 3, 5, 4),

('Konditor i det fri', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Tempor orci eu lobortis elementum. A pellentesque sit amet porttitor. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Consectetur a erat nam at lectus urna duis.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 3, 5, 5),

('Konditor i det fri', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed vulputate odio ut enim. Vitae semper quis lectus nulla at volutpat diam. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Id leo in vitae turpis massa sed elementum tempus egestas. Sed enim ut sem viverra aliquet eget sit amet. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Volutpat lacus laoreet non curabitur gravida arcu. Vitae suscipit tellus mauris a diam maecenas. Orci nulla pellentesque dignissim enim sit amet. Sit amet consectetur adipiscing elit ut aliquam purus sit. In nulla posuere sollicitudin aliquam ultrices. Eu sem integer vitae justo eget magna fermentum iaculis. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Nec feugiat nisl pretium fusce id velit ut tortor. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sit amet purus gravida quis blandit. Neque sodales ut etiam sit.

Aenean vel elit scelerisque mauris pellentesque. Nunc id cursus metus aliquam eleifend mi. Euismod quis viverra nibh cras pulvinar mattis. Egestas congue quisque egestas diam. Ipsum nunc aliquet bibendum enim. Faucibus nisl tincidunt eget nullam non nisi est sit. Fames ac turpis egestas integer eget aliquet nibh. Cras ornare arcu dui vivamus. Habitant morbi tristique senectus et netus. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Est ante in nibh mauris cursus. Sed augue lacus viverra vitae. Consequat interdum varius sit amet mattis vulputate. Id nibh tortor id aliquet lectus proin nibh. In hendrerit gravida rutrum quisque non tellus orci. Auctor augue mauris augue neque. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Erat nam at lectus urna duis convallis.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 4, 4, 3),

('Konditor i det fri', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At auctor urna nunc id cursus metus aliquam. Neque ornare aenean euismod elementum nisi quis. Integer vitae justo eget magna fermentum. Tristique magna sit amet purus gravida quis blandit. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. Gravida neque convallis a cras semper auctor neque vitae tempus. Scelerisque purus semper eget duis at tellus. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Dolor purus non enim praesent elementum facilisis. Tincidunt eget nullam non nisi est. Varius quam quisque id diam. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Laoreet id donec ultrices tincidunt arcu. Enim ut tellus elementum sagittis vitae et leo duis. Quis enim lobortis scelerisque fermentum dui faucibus in. Viverra tellus in hac habitasse platea dictumst vestibulum. Rutrum quisque non tellus orci ac auctor augue mauris. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Sed elementum tempus egestas sed sed. Leo vel fringilla est ullamcorper eget nulla. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Amet commodo nulla facilisi nullam vehicula ipsum. Lacinia at quis risus sed vulputate odio ut enim blandit.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 4, 5, 5),

('Konditor i det fri', 'na@na.dk', '01234567', 
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed vulputate odio ut enim. Vitae semper quis lectus nulla at volutpat diam. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Id leo in vitae turpis massa sed elementum tempus egestas. Sed enim ut sem viverra aliquet eget sit amet. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Volutpat lacus laoreet non curabitur gravida arcu. Vitae suscipit tellus mauris a diam maecenas. Orci nulla pellentesque dignissim enim sit amet. Sit amet consectetur adipiscing elit ut aliquam purus sit. In nulla posuere sollicitudin aliquam ultrices. Eu sem integer vitae justo eget magna fermentum iaculis. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Nec feugiat nisl pretium fusce id velit ut tortor. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sit amet purus gravida quis blandit. Neque sodales ut etiam sit.

Aenean vel elit scelerisque mauris pellentesque. Nunc id cursus metus aliquam eleifend mi. Euismod quis viverra nibh cras pulvinar mattis. Egestas congue quisque egestas diam. Ipsum nunc aliquet bibendum enim. Faucibus nisl tincidunt eget nullam non nisi est sit. Fames ac turpis egestas integer eget aliquet nibh. Cras ornare arcu dui vivamus. Habitant morbi tristique senectus et netus. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Est ante in nibh mauris cursus. Sed augue lacus viverra vitae. Consequat interdum varius sit amet mattis vulputate. Id nibh tortor id aliquet lectus proin nibh. In hendrerit gravida rutrum quisque non tellus orci. Auctor augue mauris augue neque. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Erat nam at lectus urna duis convallis.

Feugiat nisl pretium fusce id velit ut. Amet luctus venenatis lectus magna fringilla urna porttitor. Duis ut diam quam nulla porttitor massa id neque. Erat velit scelerisque in dictum non consectetur. Facilisis leo vel fringilla est ullamcorper eget. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Et ligula ullamcorper malesuada proin libero nunc consequat. Volutpat ac tincidunt vitae semper quis lectus. Mi in nulla posuere sollicitudin aliquam ultrices. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Risus nullam eget felis eget. Amet nisl purus in mollis nunc sed id semper risus. Quis varius quam quisque id diam. Lobortis mattis aliquam faucibus purus in massa. Mauris a diam maecenas sed enim ut sem viverra aliquet. Velit euismod in pellentesque massa. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Ac ut consequat semper viverra nam libero.',
'N/A', DATEADD(SECOND, @Random, @FromDate), @deadDate, 'none.com', 4, 5, 5)
GO