USE [JobAgentDB]
GO

INSERT INTO [Category]([Name])
VALUES
('Anlægsgartner'),
('Anlægsstruktør, bygningstruktør og brolægger'),
('Autolakerer'),
('Automatik- og procesuddannelsen'),
('Bager og konditoruddannelsen'),
('Beklædningshåndværker'),
('Beslagsmed'),
('Boligmonteringsuddannelsen'),
('Buschauffør i kollektiv trafik'),
('Byggemontagetekniker'),
('Bygningsmaler'),
('Bygningssnedker'),
('Bådmekaniker'),
('Cnc-teknikeruddannelsen'),
('Cykel- og motorcykelmekaniker'),
('Data- og kommunikationsuddannelsen'),
('Den pædagogiske assistentuddannelse'),
('Detailhandel'),
('Digital media'),
('Dyrepasser'),
('Ejendomsservicetekniker'),
('Elektriker'),
('Elektronik- og svagstrømsuddannelsen'),
('Elektronikoperatør'),
('Entreprenør- og landbrugsmaskinuddannelsen'),
('Ernæringsassistent'),
('Eventkoordinator'),
('Film- og tv-produktionsuddannelsen'),
('Finansuddannelsen'),
('Finmekanikeruddannelsen'),
('Fitnessuddannelse'),
('Flytekniker'),
('Forsyningsoperatør'),
('Fotograf'),
('Frisør'),
('Gartner'),
('Gastronom'),
('Glarmester'),
('Gourmetslagter'),
('Grafisk tekniker'),
('Greenkeeper'),
('Guld- og sølvsmedeuddannelsen'),
('Handelsuddannelsen'),
('Havne- og terminaluddannelsen'),
('Hospitalsteknisk assistent'),
('Industrioperatør'),
('Industrislagter'),
('Industriteknikeruddannelsen'),
('Karrosseriteknikeruddannelsen'),
('Kontoruddannelsen'),
('Kosmetiker'),
('Kranfører'),
('Køletekniker'),
('Lager- og terminaluddannelsen'),
('Landbrugsuddannelsen'),
('Lastvognsmekaniker'),
('Lufthavnsuddannelsen'),
('Maritime håndværksfag'),
('Maskinsnedker'),
('Mediegrafiker'),
('Mejerist'),
('Murer'),
('Møbelsnedker og orgelbygger'),
('Ortopædist'),
('Overfladebehandler'),
('Personvognsmekaniker'),
('Plastmager'),
('Procesoperatør'),
('Produktions- og montageuddannelsen'),
('Produktør'),
('Receptionist'),
('Redderuddannelsen'),
('Serviceassistent'),
('Sikkerhedsvagt'),
('Skibsmekaniker'),
('Skibsmontør'),
('Skiltetekniker'),
('Skorstensfejer'),
('Skov- og naturtekniker'),
('Smed'),
('Social- og sundhedsuddannelsen'),
('Stenhugger'),
('Stukkatør'),
('Støberitekniker'),
('Tagdækker'),
('Tandklinikassistent'),
('Tandtekniker'),
('Tarmrenser'),
('Teater-, udstillings- og eventtekniker'),
('Teknisk designer'),
('Teknisk isolatør'),
('Tjener'),
('Togklargøringsuddannelsen'),
('Træfagenes byggeuddannelse'),
('Turistbuschauffør'),
('Urmager'),
('Vejgodstransportuddannelsen'),
('Veterinærsygeplejerske'),
('VVS-energiuddannelsen'),
('Værktøjsuddannelsen'),
('Webudvikler'),
('Lokomotivfører'),
('Fodterapeut')
GO

INSERT INTO [Specialization]([Name], [CategoryId])
VALUES
('Automatikmontør', 4),
('Automatiktekniker', 4),
('Automatiseringstekniker', 4),
('Detailbager, håndværksbager eller konditor', 5),
('Bagværker', 5),
('Beklædningshåndværker', 6),
('Tekstil- og beklædningsassistent', 6),
('Buschauffør', 9),
('Buschauffør i kollektiv trafik', 9),
('Kørselsdisponent', 9),
('Motorcykelmekaniker', 15),
('Cykelmekaniker', 15),
('Knallertmekaniker', 15),
('Infrastruktur', 16),
('Programmering', 16),
('It-supporter', 16),
('Dyrepasser', 20),
('Ejendomsservicetekniker', 21),
('Elektronik udviklingstekniker', 23),
('Medicotekniker', 23),
('Radio-tv-fagtekniker', 23),
('Elektronikfagtekniker', 23),
('Entreprenør- og landbrugsmaskinuddannelsen', 25),
('Materielmekaniker', 25),
('Film- og tv-produktionsuddannelsen', 28),
('Film- og tv-assistent', 28),
('Finmekaniker', 30),
('Finmekanikerassistent', 30),
('Gastronom', 37),
('Gastronomassistent', 37),
('Gourmetslagter', 39),
('Gourmetslagteraspirant', 39),
('Greenkeeper', 41),
('Groundsman', 41),
('Guld- og sølvsmed', 42),
('Butiksguldsmed', 42),
('Havne- og terminalarbejder', 44),
('Havnemedhjælper', 44),
('Industrioperatør', 46),
('Industrioperatør-produktivitet', 46),
('Slagter m. speciale', 47),
('Slagter (trin 1)', 47),
('Industritekniker produktion 5', 48),
('Industritekniker maskin 4', 48),
('Industriassistent 3', 48),
('Kranfører', 52),
('Kørseldisponent', 52),
('Køletekniker', 53),
('Køleassistent', 53),
('Lager- og terminaldisponent', 54),
('Lageroperatør – lager- og transportoperatør', 54),
('Lageroperatør – lager- og logistikoperatør', 54),
('Lagermedhjælper', 54),
('Landbrugsassistent', 55),
('Landbrugsuddannelsen', 55),
('Produktionsleder', 55),
('Agrarøkonom', 55),
('Lastvognsmekaniker', 56),
('Lastvognsmontør', 56),
('Maskinsnedker', 59),
('Produktionsassistent, døre og vinduer', 59),
('Produktionsassistent, møbel', 59),
('Mejerist', 61),
('Mejerioperatør', 61),
('Møbelsnedker', 63),
('Orgelbygger', 63),
('Overfladebehandler m. speciale', 65),
('Overfladebehandler', 65),
('Personvognsmekaniker', 66),
('Personvognsmontør', 66),
('Procesoperatør', 68),
('Procesoperatør med speciale i pharma', 68),
('Procesarbejder', 68),
('Skibsmekaniker', 75),
('Skibsmontør', 76),
('Industrimontør', 76),
('Stentekniker', 82),
('Stenhugger', 82),
('Teater-, event- og av-teknisk produktionsassistent', 89),
('Teater-, event- og av-tekniker', 89),
('Teknisk designer', 90),
('Tjener', 92),
('Konference- og selskabstjener', 92),
('Klargøring og rangering af persontog', 93),
('Klargøring og rangering af godstog', 93),
('Turistbuschauffør', 95),
('Kørselsdisponent', 95),
('Godschauffør', 97),
('Renovationschauffør', 97),
('Tankbilchauffør', 97),
('Flyttechauffør', 97),
('Kørseldisponent', 97),
('Værktøjsuddannelsen', 100),
('Værktøjsmager', 100)
GO

-- SET IDENTITY_INSERT to ON.
SET IDENTITY_INSERT [dbo].[Category] ON;
GO

-- Try Insert Null values.
INSERT INTO [dbo].[Category] ([Id], [Name]) VALUES (0, Null);
GO

-- SET IDENTITY_INSERT to OFF.
SET IDENTITY_INSERT [dbo].[Category] OFF;
GO

-- SET IDENTITY_INSERT to ON.
SET IDENTITY_INSERT [dbo].[Specialization] ON;
GO

-- Try insert null values.
INSERT INTO [dbo].[Specialization] ([Id], [Name], [CategoryId]) VALUES (0, Null, 0);
GO

-- SET IDENTITY_INSERT to OFF.
SET IDENTITY_INSERT [dbo].[Specialization] OFF;
GO