name: Job Agent .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Blazor Website .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "JobAgentSolutions/BlazorWebsite/BlazorWebsite.csproj"
    - name: Build
      run: dotnet build "JobAgentSolutions/BlazorWebsite/BlazorWebsite.csproj" --no-restore
    - name: Test
      run: dotnet test "JobAgentSolutions/BlazorWebsite/BlazorWebsite.csproj" --no-build --verbosity normal
